<?php
namespace App\FormTypes;

use App\Form\DataTransformer\DateToStringTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DatePickerType extends  AbstractType
{
    private $_dateToStringTransformer = null;

    function __construct(DateToStringTransformer $dateToString)
    {
        $this->_dateToStringTransformer = $dateToString;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addModelTransformer($this->_dateToStringTransformer);
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }
    public function getParent()
    {
        return TextType::class;
    }
}